//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaBP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klijent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Klijent()
        {
            this.IzdatiKreditis = new HashSet<IzdatiKrediti>();
        }
    
        public int JMBG_KLI { get; set; }
        public string IME_KLI { get; set; }
        public string PRZ_KLI { get; set; }
        public int ZirantID_ZIR { get; set; }
        public Nullable<int> PLT_KLI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IzdatiKrediti> IzdatiKreditis { get; set; }
        public virtual Zirant Zirant { get; set; }
    }
}
