//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaBP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kompanija
    {
        public int ID_KOMP { get; set; }
        public string NETO_KOMP { get; set; }
    
        public virtual Biznis Bizni { get; set; }
    }
}
