//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaBP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kredit
    {
        public int ID_ZAHT { get; set; }
        public string VAL { get; set; }
        public string KOL_SRD { get; set; }
        public string DAT_IZD { get; set; }
        public int IzdatiKreditiKlijentJMBG_KLI { get; set; }
        public int IzdatiKreditiSluzbenikJMBG_RAD { get; set; }
        public int IzdatiKreditiOdobrenjeRISKID_KOMISIJE { get; set; }
        public int IzdatiKreditiOdobrenjeOdlukaID_ODLUKE { get; set; }
        public string tipKredita { get; set; }
    
        public virtual IzdatiKrediti IzdatiKrediti { get; set; }
    }
}
