//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaBP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odobrenje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Odobrenje()
        {
            this.IzdatiKreditis = new HashSet<IzdatiKrediti>();
        }
    
        public int RISKID_KOMISIJE { get; set; }
        public int OdlukaID_ODLUKE { get; set; }
    
        public virtual RISK RISK { get; set; }
        public virtual Odluka Odluka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IzdatiKrediti> IzdatiKreditis { get; set; }
    }
}
